SET DEFINE OFF;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PERSON';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ADDRESS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PERSON (
    personId NUMBER,
    lastName VARCHAR2(50),
    firstName VARCHAR2(50)
);

CREATE TABLE ADDRESS (
    addressId NUMBER,
    personId NUMBER,
    city VARCHAR2(50),
    state VARCHAR2(50)
);

INSERT INTO PERSON VALUES (1, 'WANG', 'ALLEN');
INSERT INTO PERSON VALUES (2, 'ALICE', 'BOB');

INSERT INTO ADDRESS VALUES (1, 2, 'New York City', 'New York');
INSERT INTO ADDRESS VALUES (2, 3, 'Leetcode', 'California');

COMMIT;

EXIT;