name: C++ CI Working Application both build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install compiler & CMake
      - name: Install compiler and CMake
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      # Show directory structure (Debug)
      - name: Show directory structure
        run: ls -R

      # Configure project with CMake
      - name: Configure String Conversion
        run: cmake -S Working_Application/String_Conversion \
                   -B Working_Application/String_Conversion/build \
                   -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      # Build application and tests
      - name: Build project
        run: cmake --build Working_Application/String_Conversion/build --parallel

      # Run tests with CTest
      - name: Run String Conversion Tests
        run: ctest --output-on-failure --test-dir Working_Application/String_Conversion/build

      # Run tests with logs
      - name: Run String Conversion Tests with Logs
        run: ./Working_Application/String_Conversion/build/runTests --gtest_output=console --gtest_brief=0