name: C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ASCII/ASCIIChart/code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile PrintableChar.cpp
        run: g++ basic.cpp -o basic

      - name: Run program
        run: ./PrintableChar
