name: C++ CI with Matrix Strategy charcater comparison

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - ASCII/CharacterComparison/code/CompareTwoCharacters
          - ASCII/CharacterComparison/code/CompareTwoCharacters_V1.1
          - ASCII/CharacterComparison/code/CompareTwoCharacters_V1.2 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile main.cpp
        working-directory: ${{ matrix.version }}
        run: g++ -std=c++17 -Wall -Wextra -O2 main.cpp -o main

      - name: Run program
        working-directory: ${{ matrix.version }}
        run: ./main

      - uses: actions/upload-artifact@v5
        with:
            name: ${{ matrix.version }}-output
            path: ${{ matrix.version }}/main