name: C++ CI with Matrix Strategy character comparison

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
       matrix:
         include:
          - name: V1
            dir: ASCII/CharacterComparison/code/CompareTwoCharacters
          - name: V1.1
            dir: ASCII/CharacterComparison/code/CompareTwoCharacters_V1.1
          - name: V1.2
            dir: ASCII/CharacterComparison/code/CompareTwoCharacters_V1.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile main.cpp
        working-directory: ${{ matrix.dir }}
        run: g++ -std=c++17 -Wall -Wextra -O2 main.cpp -o main

      - name: Run program
        working-directory: ${{ matrix.dir }}
        run: ./main

      - uses: actions/upload-artifact@v5
        with:
            name: ${{ matrix.name }}-output
            path: ${{ matrix.dir }}/main