name: C++ Leetcode 175CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install gcc  # g++ on macOS

      - name: Compile cpp_runData.cpp
        run: |
          g++ -std=c++17 -O2 Leetcode/175/cpp_runData.cpp -o Leetcode/175/cpp_runData

      - name: Run the program
        run: |
          ./Leetcode/175/cpp_runData

      - name: Success message
        run: |
          echo "C++ CI/CD pipeline ran successfully!"