name: C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        problem_dir: [Leetcode/1390, Leetcode/223]

    defaults:
      run:
        working-directory: ${{ matrix.problem_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile main.cpp
        run: g++ -std=c++17 -O2 main.cpp -o main

      - name: Run program
        run: ./main
