name: Run Oracle Scripts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  oracle:
    runs-on: ubuntu-latest

    services:
      oracle:
        image: gvenzl/oracle-xe
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: MyPlainPassword123
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for Oracle XE to start
        run: |
          echo "Waiting for Oracle XE to initialize..."
          for i in {1..20}; do
            docker exec -i ${{ job.services.oracle.id }} bash -c "echo 'SELECT 1 FROM dual;' | sql /nolog" >/dev/null 2>&1 && break
            echo "Oracle not ready, retrying in 5s..."
            sleep 5
          done
          echo "Oracle XE is ready!"

      - name: Run OracleSetup.sql
        run: |
          echo "Running OracleSetup.sql..."
          docker exec -i ${{ job.services.oracle.id }} bash -c "\
            echo 'Executing OracleSetup.sql'; \
            sqlplus -S system/MyPlainPassword123@//localhost:1521/XEPDB1 @/dev/stdin" < ./Leetcode/3497/OracleSetup.sql
      
      - name: Run OracleQuery.sql and save output
        run: |
          echo "Running OracleQuery.sql..."
          docker exec -i ${{ job.services.oracle.id }} bash -c "\
            echo 'Executing OracleQuery.sql'; \
            sqlplus -S system/MyPlainPassword123@//localhost:1521/XEPDB1 @/dev/stdin" < ./Leetcode/3497/OracleQuery.sql > oracle_query_results.csv
          echo "OracleQuery.sql executed, results saved to oracle_query_results.csv"
    
      - name: Run oracleSetup.sql
        run: |
          echo "Running oracleSetup.sql..."
          docker exec -i ${{ job.services.oracle.id }} bash -c "\
            echo 'Executing oracleSetup.sql'; \
            sqlplus -S system/MyPlainPassword123@//localhost:1521/XEPDB1 @/dev/stdin" < ./Leetcode/175/oracleSetup.sql
      
      - name: Run oracleQuery.sql and save output
        run: |
          echo "Running oracleQuery.sql..."
          docker exec -i ${{ job.services.oracle.id }} bash -c "\
            echo 'Executing oracleQuery.sql'; \
            sqlplus -S system/MyPlainPassword123@//localhost:1521/XEPDB1 @/dev/stdin" < ./Leetcode/175/oracleQuery.sql > oracle_query_results_175.csv
          echo "oracleQuery.sql executed, results saved to oracle_query_results_175.csv"
        

      - name: Upload Oracle query results
        uses: actions/upload-artifact@v4
        with:
          name: oracle-query-results
          path: oracle_query_results.csv
          
      - name: Upload Oracle query results for 175
        uses: actions/upload-artifact@v4
        with:
          name: oracle-query-results-175
          path: oracle-query-results-175.csv