name: Sync Forks Daily

on:
  schedule:
    # Runs at 08:00 AM UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync Fork
        run: |
          gh repo list nitishhsinghhh --limit 1000 --json nameWithOwner --jq '.[].nameWithOwner' | xargs -I {} gh repo sync {}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}