name: Sync Forks Daily

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Forks
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          gh repo list nitishhsinghhh --limit 1000 --json nameWithOwner,isFork --jq '.[] | select(.isFork == true) | .nameWithOwner' | xargs -I {} sh -c 'echo "Syncing {}..."; gh repo sync {} || echo "Failed to sync {}"'