name: C++ CI Working Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Install compiler & CMake
      # -------------------------------
      - name: Install compiler and CMake
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      # -------------------------------
      # Show directory structure (Debug)
      # -------------------------------
      - name: Show directory structure
        run: ls -R

      # -------------------------------
      # String Conversion App
      # -------------------------------

      - name: Debug String Conversion sources
        run: ls -l String_Conversion/src

      - name: Compile String Conversion App
        run: |
            g++ -O2 -std=c++17 -Wall -Wextra \
            -I String_Conversion/include \
            String_Conversion/src/*.cpp \
            -o String_Conversion/app


        #  Using wildcard (*.cpp) automatically includes all source files.
        #  Cleaner and easier to maintain than listing each file manually.
        #  Headers (.h) are not compiled directly — they’re included via .cpp.

      - name: Run String Conversion App
        run: ./String_Conversion/app

      # -------------------------------
      # String Conversion Tests (GoogleTest)
      # -------------------------------
      - name: Configure String Conversion Tests
        run: cmake -S String_Conversion -B String_Conversion/build

      - name: Build String Conversion Tests
        run: cmake --build String_Conversion/build

      - name: Run String Conversion Tests
        run: ctest --output-on-failure --test-dir String_Conversion/build

      - name: Run String Conversion Tests with Logs
        run: ./String_Conversion/build/runTests --gtest_output=console --gtest_brief=0
