name: C++ CI Working Application using build steps

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Install compiler & CMake
      # -------------------------------
      - name: Install compiler and CMake
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      # -------------------------------
      # Show directory structure (Debug)
      # -------------------------------
      - name: Show directory structure
        run: ls -R

      # -------------------------------
      # Configure project with CMake
      # -------------------------------
      - name: Configure String Conversion
        run: cmake -S Working_Application/String_Conversion -B Working_Application/String_Conversion/build -DCMAKE_BUILD_TYPE=Release

      # -------------------------------
      # Build application and tests
      # -------------------------------
      - name: Build project
        run: cmake --build Working_Application/String_Conversion/build --parallel

      # -------------------------------
      # Run the main application
      # -------------------------------
      - name: Run String Conversion App
        run: ./Working_Application/String_Conversion/build/app

      # -------------------------------
      # Run tests with CTest
      # -------------------------------
      - name: Run String Conversion Tests
        run: ctest --output-on-failure --test-dir Working_Application/String_Conversion/build

      - name: Run String Conversion Tests with Logs
        run: ./Working_Application/String_Conversion/build/runTests --gtest_output=console --gtest_brief=0
